# -*- coding: utf-8 -*-
"""AI - Powered Emotion Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UZkwMwFEvT9aL-IRmum5TkuifMN_sru0

## Installing Required Libraries
"""

!pip install datasets

!pip install pandas numpy scikit-learn nltk seaborn matplotlib torch transformers datasets

"""## Loading The Dataset"""

from google.colab import files
uploaded = files.upload()

from datasets import load_dataset

dataset = load_dataset(
    "csv",
    data_files={
        "train": "train.csv",
        "validation": "validation.csv",
        "test": "test.csv"
    }
)

print(dataset)

dataset['train']
dataset['validation']
dataset['test']

train_df = dataset['train'].to_pandas()
val_df   = dataset['validation'].to_pandas()
test_df  = dataset['test'].to_pandas()

train_df.head()

train_df.info()

"""## Data Cleaning"""

train_df.isnull().sum()

train_df.duplicated().sum()

train_df.drop_duplicates(inplace=True)

train_df.duplicated().sum()

train_df.describe()

print(dataset["train"][:5])

dataset["train"].features

len(dataset['train'])

sum([1 for x in dataset['train'] if x['text'] is None])

from datasets import ClassLabel

class_names = ["sadness", "joy", "love", "anger", "fear", "surprise"]

dataset = dataset.cast_column("label", ClassLabel(names=class_names))

dataset["train"].features["label"].names

from collections import Counter

labels = dataset["train"]["label"]
label_counts = Counter(labels)

for label_id, count in label_counts.items():
    emotion = dataset["train"].features["label"].names[label_id]
    print(f"{emotion}: {count}")

"""## Exploratory Data Analysis(EDA)"""

from collections import Counter
import matplotlib.pyplot as plt

labels = dataset["train"]["label"]

# Count labels
label_counts = Counter(labels)

# Map label IDs to emotion names
label_names = dataset["train"].features["label"].names

emotions = [label_names[i] for i in label_counts.keys()]
counts = [label_counts[i] for i in label_counts.keys()]

# Plot
plt.bar(emotions, counts)
plt.title("Emotion Label Distribution")
plt.xlabel("Emotion")
plt.ylabel("Count")
plt.show()

train_df['text_length'] = train_df['text'].apply(len)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.hist(train_df['text_length'], bins=50)
plt.title("Text Length Distribution")
plt.xlabel("Length of Text")
plt.ylabel("Frequency")
plt.show()

train_df['word_count'] = train_df['text'].apply(lambda x: len(x.split()))

plt.figure(figsize=(8,5))
plt.hist(train_df['word_count'], bins=50)
plt.title("Word Count Distribution")
plt.xlabel("Number of Words")
plt.ylabel("Frequency")
plt.show()

train_df['label'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Class Distribution")
plt.ylabel('')
plt.show()

from collections import Counter

all_words = " ".join(train_df['text']).split()
common_words = Counter(all_words).most_common(10)

words, counts = zip(*common_words)

plt.figure(figsize=(8,5))
plt.bar(words, counts)
plt.xticks(rotation=45)
plt.title("Top 10 Most Common Words")
plt.show()

"""## 1. TF-IDF + Logistic Regression Model"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Train
X_train = dataset["train"]["text"]
y_train = dataset["train"]["label"]

X_test = dataset["test"]["text"]
y_test = dataset["test"]["label"]

tfidf = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1, 2),
    stop_words="english"
)

X_train_tfidf = tfidf.fit_transform(X_train)

X_test_tfidf = tfidf.transform(X_test)

model = LogisticRegression(max_iter=1000)

model.fit(X_train_tfidf, y_train)

y_pred = model.predict(X_test_tfidf)

test_acc_lr = accuracy_score(y_test, y_pred)

print("Logistic Regression Test Accuracy:", test_acc_lr)

label_names = ["sadness", "joy", "love", "anger", "fear", "surprise"]

print(classification_report(
    y_test,
    y_pred,
    target_names=label_names
))

"""## 2. LSTM Model"""

X_train = dataset["train"]["text"]
y_train = dataset["train"]["label"]

X_val = dataset["validation"]["text"]
y_val = dataset["validation"]["label"]

X_test = dataset["test"]["text"]
y_test = dataset["test"]["label"]

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

vocab_size = 15000
max_len = 200

tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_val_seq   = tokenizer.texts_to_sequences(X_val)
X_test_seq  = tokenizer.texts_to_sequences(X_test)

X_train_pad = pad_sequences(X_train_seq, maxlen=max_len, padding="post")
X_val_pad   = pad_sequences(X_val_seq, maxlen=max_len, padding="post")
X_test_pad  = pad_sequences(X_test_seq, maxlen=max_len, padding="post")

import numpy as np

y_train = np.array(y_train)
y_val   = np.array(y_val)
y_test  = np.array(y_test)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional

model = Sequential([
    Embedding(vocab_size, 128),

    Bidirectional(LSTM(128, return_sequences=True)),
    Dropout(0.5),

    Bidirectional(LSTM(64)),
    Dropout(0.5),

    Dense(64, activation='relu'),
    Dropout(0.5),

    Dense(6, activation='softmax')
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    X_train_pad,
    y_train,
    epochs=15,
    batch_size=64,
    validation_data=(X_val_pad, y_val)
)

test_loss, test_acc_lstm = model.evaluate(X_test_pad, y_test)
print("LSTM Test Accuracy:", test_acc_lstm)

label_names = ["sadness", "joy", "love", "anger", "fear", "surprise"]
num_labels = 6

"""## 3. DISTILBERT Model"""

from transformers import DistilBertTokenizerFast

tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

def tokenize(batch):
    return tokenizer(
        batch["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

tokenized_dataset = dataset.map(tokenize, batched=True)

tokenized_dataset = tokenized_dataset.remove_columns(["text"])
tokenized_dataset = tokenized_dataset.rename_column("label", "labels")
tokenized_dataset.set_format("torch")

from transformers import DistilBertForSequenceClassification

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=num_labels
)

import numpy as np
from sklearn.metrics import accuracy_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {"accuracy": accuracy_score(labels, preds)}

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    load_best_model_at_end=True,
)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    compute_metrics=compute_metrics
)

"""## DISTILBERT Model Training"""

trainer.train()

results = trainer.evaluate(tokenized_dataset["test"])

test_acc_bert = results["eval_accuracy"]

print("DistilBERT Test Accuracy:", test_acc_bert)

"""## Confusion Matrix"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

preds = trainer.predict(tokenized_dataset["test"])

y_pred = preds.predictions.argmax(axis=1)
y_true = preds.label_ids

cm = confusion_matrix(y_true, y_pred)

disp = ConfusionMatrixDisplay(cm, display_labels=label_names)
disp.plot(xticks_rotation=45)
plt.show()

trainer.save_model("./emotion_model")
tokenizer.save_pretrained("./emotion_model")

"""## Models Comparison"""

import pandas as pd

performance_df = pd.DataFrame({
    "Model": ["TF-IDF + Logistic Regression", "LSTM", "DistilBERT"],
    "Accuracy": [test_acc_lr, test_acc_lstm, test_acc_bert],
    "Type": ["Traditional ML", "Deep Learning", "Transformer"],
    "Training Time": ["Fast", "Medium", "Slow"],
    "Performance Level": ["Very Good", "Very Good", "Best"]
})

performance_df

"""## Deployment"""

from transformers import pipeline
from IPython.display import display, HTML

classifier = pipeline(
    "text-classification",
    model="./emotion_model",
    tokenizer="./emotion_model"
)

label_map = {
    0: "sadness",
    1: "joy",
    2: "love",
    3: "anger",
    4: "fear",
    5: "surprise"
}

def predict_emotion_ui(text):
    result = classifier(text)[0]

    label_index = int(result["label"].split("_")[1])
    emotion = label_map[label_index].upper()
    confidence = result["score"]

    html_output = f"""
    <div style="
        font-family: Arial;
        width: 600px;
        margin: 20px auto;
        padding: 25px;
        border-radius: 30px;
        background: linear-gradient(135deg, #f5f7fa, #c3cfe2);
        box-shadow: 0 8px 20px rgba(0,0,0,0.2);
    ">
        <h2 style="text-align:center;">Emotion Detection</h2>

        <div style="
            background: white;
            padding: 15px;
            border-radius: 20px;
            margin-top: 10px;
        ">
            {text}
        </div>

        <div style="
            margin-top: 20px;
            padding: 20px;
            border-radius: 25px;
            background: linear-gradient(135deg, #d4edda, #a8e6cf);
            color: #155724;
            text-align: center;
            font-size: 18px;
        ">
            <b>Emotion:</b> {emotion} <br><br>
            <b>Confidence:</b> {confidence:.2f}
        </div>
    </div>
    """

    display(HTML(html_output))

import ipywidgets as widgets
from IPython.display import display


text_input = widgets.Textarea(
    placeholder="Enter your text...",
    layout=widgets.Layout(width='600px', height='100px')
)

# Button
button = widgets.Button(description="Detect Emotion", button_style='success')

# Output
output = widgets.Output()

def on_click(b):
    with output:
        output.clear_output()
        text = text_input.value

        if text.strip() == "":
            print("Please enter some text!")
        else:
            predict_emotion_ui(text)

button.on_click(on_click)

display(text_input, button, output)